version: "3.9"
services:
  postgres:
    image: "postgres"
    container_name: "website_postgres_1"
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - ./_postgres-data:/var/lib/postgresql/data