name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5

      - name: Clone submodule
        run: |
          git submodule init
          git submodule update

      - name: Install
        run: npm install
        
      - name: Run tests
        run:  npm run test:cov
  
      - name: Upload coverage
        uses: codecov/codecov-action@v1.2.1
        with:
          file: ./coverage/coverage-final.json
          fail_ci_if_error: true
